// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TowerDefense.Api.Data;

#nullable disable

namespace TowerDefense.Api.Migrations
{
    [DbContext(typeof(TowerDefenseDbContext))]
    [Migration("20260622143623_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TowerDefense.Api.Models.EnemyConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseHealth")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_health");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DamageToPlayer")
                        .HasColumnType("int")
                        .HasColumnName("damage_to_player");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<decimal>("MoveSpeed")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("move_speed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("enemy_configurations", null, t =>
                        {
                            t.HasCheckConstraint("CK_enemy_base_health", "`base_health` > 0");

                            t.HasCheckConstraint("CK_enemy_damage_to_player", "`damage_to_player` > 0");

                            t.HasCheckConstraint("CK_enemy_move_speed", "`move_speed` > 0");
                        });
                });

            modelBuilder.Entity("TowerDefense.Api.Models.MatchHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("CoinsReward")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("coins_reward");

                    b.Property<DateTime>("EndedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("ended_at");

                    b.Property<long>("PlayerProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_profile_id");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("result");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("started_at");

                    b.HasKey("Id");

                    b.HasIndex("EndedAt");

                    b.HasIndex("PlayerProfileId");

                    b.ToTable("match_histories", null, t =>
                        {
                            t.HasCheckConstraint("CK_match_coins_reward", "`coins_reward` >= 0");

                            t.HasCheckConstraint("CK_match_result", "`result` IN ('Win', 'Lose')");

                            t.HasCheckConstraint("CK_match_time", "`ended_at` >= `started_at`");
                        });
                });

            modelBuilder.Entity("TowerDefense.Api.Models.PlayerProfile", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<long>("Coins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("coins");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("display_name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("player_profiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_player_profiles_coins", "`coins` >= 0");
                        });
                });

            modelBuilder.Entity("TowerDefense.Api.Models.PlayerTowerUpgrade", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("PlayerProfileId")
                        .HasColumnType("bigint")
                        .HasColumnName("player_profile_id");

                    b.Property<long>("TowerConfigurationId")
                        .HasColumnType("bigint")
                        .HasColumnName("tower_configuration_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<int>("UpgradeLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("upgrade_level");

                    b.HasKey("Id");

                    b.HasIndex("TowerConfigurationId");

                    b.HasIndex("PlayerProfileId", "TowerConfigurationId")
                        .IsUnique();

                    b.ToTable("player_tower_upgrades", null, t =>
                        {
                            t.HasCheckConstraint("CK_tower_upgrade_level", "`upgrade_level` >= 0");
                        });
                });

            modelBuilder.Entity("TowerDefense.Api.Models.TowerConfiguration", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<decimal>("BaseAttackInterval")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_attack_interval");

                    b.Property<decimal>("BaseDamage")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_damage");

                    b.Property<decimal>("BaseRange")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_range");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("tower_configurations", null, t =>
                        {
                            t.HasCheckConstraint("CK_tower_attack_interval", "`base_attack_interval` > 0");

                            t.HasCheckConstraint("CK_tower_base_damage", "`base_damage` > 0");

                            t.HasCheckConstraint("CK_tower_base_range", "`base_range` > 0");
                        });
                });

            modelBuilder.Entity("TowerDefense.Api.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Role");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("CK_users_role", "`role` IN ('Player', 'Administrator')");
                        });
                });

            modelBuilder.Entity("TowerDefense.Api.Models.MatchHistory", b =>
                {
                    b.HasOne("TowerDefense.Api.Models.PlayerProfile", "PlayerProfile")
                        .WithMany("MatchHistories")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerProfile");
                });

            modelBuilder.Entity("TowerDefense.Api.Models.PlayerProfile", b =>
                {
                    b.HasOne("TowerDefense.Api.Models.User", "User")
                        .WithOne("PlayerProfile")
                        .HasForeignKey("TowerDefense.Api.Models.PlayerProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TowerDefense.Api.Models.PlayerTowerUpgrade", b =>
                {
                    b.HasOne("TowerDefense.Api.Models.PlayerProfile", "PlayerProfile")
                        .WithMany("TowerUpgrades")
                        .HasForeignKey("PlayerProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TowerDefense.Api.Models.TowerConfiguration", "TowerConfiguration")
                        .WithMany("PlayerUpgrades")
                        .HasForeignKey("TowerConfigurationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlayerProfile");

                    b.Navigation("TowerConfiguration");
                });

            modelBuilder.Entity("TowerDefense.Api.Models.PlayerProfile", b =>
                {
                    b.Navigation("MatchHistories");

                    b.Navigation("TowerUpgrades");
                });

            modelBuilder.Entity("TowerDefense.Api.Models.TowerConfiguration", b =>
                {
                    b.Navigation("PlayerUpgrades");
                });

            modelBuilder.Entity("TowerDefense.Api.Models.User", b =>
                {
                    b.Navigation("PlayerProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
